version: '2'
services:
    influx:
        image: influxdb
        ports:
            - "8086:8086"

    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: chariot
            MYSQL_DATABASE: chariot
            MYSQL_USER: chariot
            MYSQL_PASSWORD: chariot

    app:
        build: src/app
        links:
            - db
            - influx
        volumes:
            - ./src/app:/app
            - /media
            - /static

    web:
        restart: always
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - app
        volumes:
            - ./src/conf/nginx${CONF_TAG}.conf:/etc/nginx/nginx.conf:ro
            - ./cert/certs:/cert
            - ./src/www:/www
        volumes_from:
            - app

    cert:
        image: gordonchan/auto-letsencrypt
        links:
            - web
        volumes:
            - ./cert/certs:/etc/nginx/certs
            - ./cert:/etc/letsencrypt
            - ./src/www:/var/www
        environment:
            - EMAIL
            - CERTS_PATH=/etc/nginx/certs
            - DOMAINS
            - CHECK_FREQ=3
        restart: ${CERT_RESTART}
