# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_deployment_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='safeguards_on',
            field=models.BooleanField(default=False),
        ),
    ]
