# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0005_deployment_safeguards_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsensor',
            name='safeguard_temp_lower',
            field=models.FloatField(default=17),
        ),
        migrations.AddField(
            model_name='deploymentsensor',
            name='safeguard_temp_upper',
            field=models.FloatField(default=25),
        ),
    ]
