# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0007_deploymentsensor_last_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='advisor_email',
            field=models.EmailField(blank=True, help_text='Only complete if advisors need to receive advisor safeguarding notifications', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='advisor_phone',
            field=models.CharField(blank=True, help_text='Only complete if you want too receive advisor safeguarding notifications', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='client_email',
            field=models.EmailField(blank=True, help_text='Only complete if a client need to receive safeguarding notifications', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='client_phone',
            field=models.CharField(blank=True, help_text='Only complete if a client needs to receive safeguarding notifications', max_length=20, null=True),
        ),
    ]
