# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0009_auto_20171009_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsensor',
            name='last_advisor_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
