# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0010_deploymentsensor_last_advisor_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentsensor',
            name='notifications_on',
            field=models.BooleanField(default=False),
        ),
    ]
